### ISSUE TITLE
Send summary of features

### ISSUE THREAD

**Issue by DarleenF** [kimmiet/Woozie#7]
Summary of App features 1.28.18.docx

**Comment by DarleenF** [comment]
[Summary.of.App.features.1.28.18.docx](https://github.com/kimmiet/Woozie/files/1701180/Summary.of.App.features.1.28.18.docx)

**Comment by kimmiet** [comment]
[Summary.of.App.features.2.12.18.docx](https://github.com/kimmiet/Woozie/files/1718003/Summary.of.App.features.2.12.18.docx)

**Comment by ekegulskiy** [comment]
4 features that we are committing to:
1. Calculation of BAC
2. Geolocation
3. Intoxicated speech detection
4. CheckPoint simulation: step-counting game

Stretched objectives:
1. Include eye tracking if possible to use C++ library
2. Image recognition for intoxication detection
3. Additional checkpoint simulation games, e.g. using Gyroscope for balance check

**Comment by ekegulskiy** [comment]
completed

**Comment by DXNXVAN** [comment]
GOOGLE DOC LINK: https://docs.google.com/document/d/1E0-ftTTn4mhmuVhtvm773gjdrMfn9nC5pGJBffn5AW0/edit
